/// Flutter icons CodeSwipe
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CodeSwipe
///      fonts:
///       - asset: fonts/CodeSwipe.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CodeSwipeIcons {
  CodeSwipeIcons._();

  static const _kFontFam = 'CodeSwipe';
  static const String? _kFontPkg = null;

  static const IconData twitter =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
